/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ebankclient.view;

import azio.textfieldvalidation.Validation;
import ebankclient.controller.CustomerController;
import ebankclient.model.Customer;
import java.awt.Component;
import java.awt.Container;
import java.awt.FocusTraversalPolicy;
import java.io.IOException;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class UpdateCustomer extends javax.swing.JDialog {

    private CustomerListView customerListView;

    private Customer customer = new Customer();
    private CustomerController customerController = new CustomerController();

    /**
     * Creates new form UpdateCustomer
     */
    public UpdateCustomer(java.awt.Frame parent, boolean modal, int id, CustomerListView customerListView) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        Validation.validateInt(txtAccNo);
        Validation.validateInt(txtTel);
        Validation.validateChar(txtCusName);
        Validation.validateInt(txtSCode);
        Validation.validateInt(txtCardNo);
        Validation.validatelength(txtCardNo, 19);
        Validation.validatelength(txtTel, 15);
        Validation.validatelength(txtAccNo, 15);
        Validation.validatelength(txtSCode, 6);
        Validation.validateInt(txtBalance);

        setFocus(this);
        this.customerListView = customerListView;
        getCustomer(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        txtCusName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        cmbDob = new org.freixas.jcalendar.JCalendarCombo();
        jLabel12 = new javax.swing.JLabel();
        txtAccNo = new javax.swing.JTextField();
        txtSCode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        txtCardNo = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cmbAccType = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update Customer Details");

        jLabel6.setText("Email");

        txtCusName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCusNameKeyReleased(evt);
            }
        });

        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAddressKeyReleased(evt);
            }
        });

        jLabel12.setText("Card");

        txtAccNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAccNoKeyReleased(evt);
            }
        });

        txtSCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSCodeKeyReleased(evt);
            }
        });

        jLabel1.setText("Customer Name");

        txtBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBalanceActionPerformed(evt);
            }
        });
        txtBalance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBalanceKeyReleased(evt);
            }
        });

        txtCardNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCardNoKeyReleased(evt);
            }
        });

        btnUpdate.setText("Update Customer");
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel2.setText("Date of birth");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Update Customer");

        jLabel3.setText("Address");

        txtTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelKeyReleased(evt);
            }
        });

        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });

        jLabel7.setText("Account type");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        cmbAccType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Checking account", "Savings account" }));

        jLabel8.setText("Account No");

        jLabel10.setText("Sort Code");

        jLabel11.setText("Balance");

        jLabel4.setText("Telephone No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTel)
                    .addComponent(txtAddress, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCusName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbDob, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(txtEmail))
                .addGap(18, 77, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAccNo)
                            .addComponent(txtBalance)
                            .addComponent(txtSCode)
                            .addComponent(txtCardNo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbAccType, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 58, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUpdate)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(248, 248, 248))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCusName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(cmbAccType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(txtAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(txtSCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(txtCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(btnUpdate))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(cmbDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3))
                                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCusNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCusNameKeyReleased
        checkEmpty();
    }//GEN-LAST:event_txtCusNameKeyReleased

    private void txtAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyReleased
        checkEmpty();
    }//GEN-LAST:event_txtAddressKeyReleased

    private void txtAccNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAccNoKeyReleased
        checkEmpty();
    }//GEN-LAST:event_txtAccNoKeyReleased

    private void txtSCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSCodeKeyReleased
        checkEmpty();
    }//GEN-LAST:event_txtSCodeKeyReleased

    private void txtBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBalanceActionPerformed

    private void txtBalanceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBalanceKeyReleased
        checkEmpty();
    }//GEN-LAST:event_txtBalanceKeyReleased

    private void txtCardNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCardNoKeyReleased
        checkEmpty();
    }//GEN-LAST:event_txtCardNoKeyReleased

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String name = txtCusName.getText();
        DateFormat formatDate = new SimpleDateFormat("yyyy-MM-dd");
        String dob = formatDate.format(cmbDob.getDate());

        String address = txtAddress.getText();
        String telNo = txtTel.getText();
        String email = txtEmail.getText();
        String accNo = txtAccNo.getText();
        int accountType = cmbAccType.getSelectedIndex();
        String sortCode = txtSCode.getText();
        Double balance = Double.parseDouble(txtBalance.getText());
        String cardNo = txtCardNo.getText();

        customer.setName(name);
        customer.setDob(dob);
        customer.setAddress(address);
        customer.setContactNo(telNo);
        customer.setEmail(email);
        customer.setAccountNo(accNo);
        customer.setAccountType(accountType);
        customer.setBalance(BigDecimal.valueOf(balance));
        customer.setSortCode(sortCode);
        customer.setCardNo(cardNo);

        try {
            customerController.update(customer);
            JOptionPane.showMessageDialog(null, "Customer Updated", "Success", JOptionPane.INFORMATION_MESSAGE);
            customerListView.getAllCustomers();
            this.dispose();

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        } catch (RuntimeException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtTelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelKeyReleased
        checkEmpty();
    }//GEN-LAST:event_txtTelKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        checkEmpty();
    }//GEN-LAST:event_txtEmailKeyReleased

    private void setFocus(UpdateCustomer dialog) {
        Component[] focusList;
        focusList = new Component[]{txtCusName, cmbDob, txtAddress, txtTel, txtEmail, cmbAccType, txtAccNo, txtSCode, txtBalance, txtCardNo, btnUpdate};

        dialog.setFocusTraversalPolicy(new FocusTraversalPolicy() {
            int focusNumber = 0;

            @Override
            public Component getLastComponent(Container aContainer) {
                return focusList[focusList.length - 1];
            }

            @Override
            public Component getFirstComponent(Container aContainer) {
                return focusList[0];
            }

            @Override
            public Component getDefaultComponent(Container aContainer) {
                return focusList[1];
            }

            @Override
            public Component getComponentAfter(Container focusCycleRoot,
                    Component aComponent) {
                focusNumber = (focusNumber + 1) % focusList.length;
                if (focusList[focusNumber].isEnabled() == false) {
                    getComponentAfter(focusCycleRoot, focusList[focusNumber]);
                }
                return focusList[focusNumber];
            }

            @Override
            public Component getComponentBefore(Container focusCycleRoot,
                    Component aComponent) {
                focusNumber = (focusList.length + focusNumber - 1)
                        % focusList.length;
                if (focusList[focusNumber].isEnabled() == false) {
                    getComponentBefore(focusCycleRoot, focusList[focusNumber]);
                }
                return focusList[focusNumber];
            }

        });
    }

    private void checkEmpty() {
        String name = txtCusName.getText();
        String address = txtAddress.getText();
        String telNo = txtTel.getText();
        String email = txtEmail.getText();
        String accNo = txtAccNo.getText();
        String sortCode = txtSCode.getText();
        String balance = txtBalance.getText();
        String cardNo = txtCardNo.getText();

        if (!name.isEmpty() && !address.isEmpty()
                && !telNo.isEmpty() && !email.isEmpty() && !accNo.isEmpty()
                && !sortCode.isEmpty() && !balance.isEmpty() && !cardNo.isEmpty()) {
            btnUpdate.setEnabled(true);
        } else {
            btnUpdate.setEnabled(false);
        }

    }

    private void getCustomer(int id) {
        try {
            Customer c = new Customer();
            c.setId(id);
            customer = customerController.get(c);
            String name = customer.getName();

            String dob = customer.getDob();
            java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(dob);
            cmbDob.setDate(date);
            String address = customer.getAddress();
            String telNo = customer.getContactNo();
            String email = customer.getEmail();
            String accNo = customer.getAccountNo();
            int accountType = customer.getAccountType();
            String sortCode = customer.getSortCode();
            String balance = customer.getBalance() + "";
            String cardNo = customer.getCardNo();

            txtCusName.setText(name);
            txtAddress.setText(address);
            txtTel.setText(telNo);
            txtEmail.setText(email);
            txtAccNo.setText(accNo);
            txtSCode.setText(sortCode);
            cmbAccType.setSelectedItem(accountType);
            txtBalance.setText(balance);
            txtCardNo.setText(cardNo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbAccType;
    private org.freixas.jcalendar.JCalendarCombo cmbDob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtAccNo;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtCardNo;
    private javax.swing.JTextField txtCusName;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtSCode;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
